name: CI Demo PortTrack

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  backend-ci:
    name: CI Backend (Python + Docker)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Instalar dependencias
        run: |
          pip install --no-cache-dir -r backend/requirements.txt

      - name: Ejecutar pruebas unitarias (pytest)
        run: |
          pytest backend/tests --maxfail=1 --disable-warnings -q

      - name: Construir imagen Docker
        run: |
          docker build -t porttrack-backend ./backend

      - name: Probar contenedor Docker
        run: |
          docker run -d -p 5000:5000 --name backend porttrack-backend
          sleep 5
          curl --fail http://localhost:5000/status

  frontend-deploy:
    name: Despliegue Frontend (GitHub Pages)
    runs-on: ubuntu-latest
    needs: backend-ci
    steps:
      - name: Checkout repositorio
        uses: actions/checkout@v3

      - name: Configurar Node.js (para validaciones opcionales)
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Validar archivos frontend (opcional)
        run: |
          echo "Validación de estructura frontend completada"

      - name: Desplegar en GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend

 
